main:
  - name: About
    url: '#about'
    weight: 1
  - name: Experience
    url: '#experience'
    weight: 2
  # - name: Posts
  #   url: /posts/
  #   weight: 2
  # - name: Docs
  #   url: /docs/
  #   weight: 3